---

name:
    immortal-queue
version:
    0.1.0.0
github:
    prikhi/immortal-queue
homepage:
    https://github.com/prikhi/immortal-queue#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Concurrency
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Build a pool of queue-processing worker threads.

description: |
    @immortal-queue@ is a library for build an asynchronous worker pool that
    processes action from a generic queue. You can use any thread-safe datatype
    with a push and pop like a @TQueue@ or a @persistent@ database table.

    The worker pool is configured by building an @ImmortalQueue@ type, which
    describes how to push and pop from the queue as well as how to process
    items and handle errors.

    For a simple usage example using a TQueue, see the module documentation.
    For a more complex example that uses a @persistent@ database as a queue,
    see
    <https://github.com/Southern-Exposure-Seed-Exchange/southernexposure.com/blob/develop/server/src/Workers.hs Southern Exposure's website code>.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - async
        - immortal

tests:
    immortal-queue-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - immortal-queue
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
